# Generated by Django 2.2.4 on 2019-09-12 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0012_stmapping'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentmodell',
            name='dob',
            field=models.CharField(max_length=50),
        ),
    ]
